# This is a template `pyproject.toml` file for snaps
# This file is managed by bootstack-charms-spec and should not be modified
# within individual snap repos. https://launchpad.net/bootstack-charms-spec

[tool.flake8]
ignore = ["C901", "D100", "D101", "D102", "D103", "W503", "W504"]
exclude = ['.eggs', '.git', '.tox', '.venv', '.build', 'build', 'report', 'docs']
max-line-length = 99
max-complexity = 10
extend-ignore = ["E203", "E704"]

[tool.black]
line-length = 99
exclude = '''
/(
    | .eggs
    | .git
    | .tox
    | .venv
    | .build
    | build
    | report
    | docs
)/
'''

[tool.isort]
profile = "black"
skip_glob = [
    ".eggs",
    ".git",
    ".tox",
    ".venv",
    ".build",
    "build",
    "report",
    "docs"
]

[tool.pylint]
max-line-length = 99
load-plugins = "pylint.extensions.docparams"
ignore-paths = [
    ".eggs",
    ".git",
    ".tox",
    ".venv",
    ".build",
    "build",
    "report",
    "tests",
    "docs"
]
no-docstring-rgx = "__.*__"
default-docstring-type = "sphinx"
accept-no-param-doc = false
accept-no-raise-doc = false
accept-no-return-doc = false
accept-no-yields-doc = false

[tool.mypy]
warn_unused_ignores = true
warn_unused_configs = true
warn_unreachable = true
disallow_untyped_defs = true
ignore_missing_imports = true
exclude = [
    ".eggs",
    ".git",
    ".tox",
    ".venv",
    ".build",
    "build",
    "lib",
    "report",
    "tests",
    "docs"
]

[tool.coverage.run]
relative_files = true
concurrency = ["gevent"]
source = ["."]
omit = [
    "tests/**",
    "docs/**",
    "lib/**",
    "snap/**",
    "build/**",
    "setup.py",
]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.html]
directory = "tests/unit/report/html"

[tool.coverage.xml]
output = "tests/unit/report/coverage.xml"

[tool.codespell]
skip = ".eggs,.tox,.git,.venv,venv,build,.build,lib,report,docs"
quiet-level = 3
check-filenames = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::RuntimeWarning",
]
